apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: coroot
  namespace: coroot
spec:
  to:
    kind: Service
    name: coroot-coroot
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
